apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.common.name }}
  ports:
    - name: 3001-3001
      nodePort: 30080
      port: {{ .Values.common.port }}
      protocol: TCP
      targetPort: {{ .Values.common.port }}
