apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-configmap
data:
  PORT: {{ .Values.common.port }}
  URL: 0.0.0.0
  POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
