apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.common.port }}
      targetPort: {{ .Values.common.port }}
  selector:
    app: {{ .Values.common.name }}
