apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-configmap
data:
  PORT: {{ .Values.common.port }}
  URL: 0.0.0.0
  MONGO_URL: mongodb://mongodb:27017/
  PAYMENT_GRPC_URL: payment
  PAYMENT_GRPC_PORT: 5003
