apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubetools

commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/component: prometheus
  app.kubernetes.io/part-of: prometheus
  app.kubernetes.io/managed-by: kustomize

resources:
- deployment.yaml
- service.yaml

