apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.common.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.common.name }}
  ports:
    - port: {{ .Values.common.port }}
