apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: payment
        version: v1
        project: kubetools
    spec:
      containers:
        - name: kubetools-payment
          image: vladmorzhanov/kubetools_payment:1.0.5
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: PORT
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: URL
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: POSTGRES_URL
