apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
  namespace: kubetools
spec:
  ports:
    - name: grpc-payment
      port: 5003
      targetPort: 5003
  selector:
    app: payment
