apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
  labels:
    app: elk
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: elk
        version: v1
        project: kubetools
    spec:
      serviceAccountName: elk
      containers:
        - name: kubetools_es
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        - name: kubetools_filebeat
          image: docker.elastic.co/beats/filebeat:7.2.0
        - name: kubetools_kibana
          image: docker.elastic.co/kibana/kibana:7.2.0
