apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
  labels:
    app: apigw
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: apigw
        version: v1
        project: kubetools
    spec:
      containers:
        - name: kubetools-apigw
          image: vladmorzhanov/kubetools_apigw:1.0.1
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: apigw-configmap
                  key: PORT
            - name: ORDER_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: apigw-configmap
                  key: ORDER_GRPC_URL
            - name: ORDER_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: apigw-configmap
                  key: ORDER_GRPC_PORT
            - name: PAYMENT_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: apigw-configmap
                  key: PAYMENT_GRPC_URL
            - name: PAYMENT_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: apigw-configmap
                  key: PAYMENT_GRPC_PORT
