apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubetools

commonLabels:
  app.kubernetes.io/name: apigw
  app.kubernetes.io/component: apigw
  app.kubernetes.io/part-of: apigw
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: apigw-configmap
    envs:
      - .env

resources:
- deployment.yaml
- service.yaml
