commonLabels:
  app.kubernetes.io/name: apigw
  app.kubernetes.io/component: apigw
  app.kubernetes.io/part-of: apigw
  app.kubernetes.io/managed-by: kustomize

resources:
- deployment.yaml
- service.yaml
