apiVersion: v1
kind: Service
metadata:
  name: apigw
  namespace: kubetools
spec:
  type: NodePort
  selector:
    app: apigw
  ports:
    - name: http-apigw
      nodePort: 30080
      port: 3001
      protocol: TCP
      targetPort: 3001
