apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: grafana
        version: v1
        project: kubetools
    spec:
      containers:
        - name: kubetools-grafana
          image: grafana/grafana:6.7.2
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: grafana-configmap
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: grafana-configmap
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              valueFrom:
                configMapKeyRef:
                  name: grafana-configmap
                  key: GF_USERS_ALLOW_SIGN_UP
