apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubetools

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: grafana
  app.kubernetes.io/part-of: grafana
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: grafana-configmap
    envs:
      - .env

resources:
- deployment.yaml
- service.yaml
