apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.common.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.common.name }}
  ports:
    - name: udp
      protocol: UDP
      port: {{ .Values.ports.udp }}
      targetPort: {{ .Values.ports.udp }}
    - name: tcp
      protocol: TCP
      port: {{ .Values.ports.tcp }}
      targetPort: {{ .Values.ports.tcp }}
    - name: tcp2
      protocol: TCP
      port: {{ .Values.ports.tcp2 }}
      targetPort: {{ .Values.ports.tcp2 }}
