apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - name: udp
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: tcp
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: tcp2
      protocol: TCP
      port: 14268
      targetPort: 14268
  selector:
    app: jaeger
