apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: postgres
        version: v1
        project: kubetools
    spec:
      containers:
        - name: kubetools-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_PASSWORD
