apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: mongodb
        version: v1
        project: kubetools
    spec:
      containers:
        - name: kubetools-mongodb
          image: docker.io/bitnami/mongodb:4.4
          ports:
            - containerPort: 27017
