apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
    version: v1
    project: kubetools
  namespace: kubetools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
      project: kubetools
  template:
    metadata:
      labels:
        app: order
        version: v1
        project: kubetools
    spec:
      containers:
        - name: kubetools-order
          image: vladmorzhanov/kubetools_order:1.0.5
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: PORT
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: URL
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: MONGO_URL
            - name: PAYMENT_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: PAYMENT_GRPC_URL
            - name: PAYMENT_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: PAYMENT_GRPC_PORT
