apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubetools

commonLabels:
  app.kubernetes.io/name: order
  app.kubernetes.io/component: order
  app.kubernetes.io/part-of: order
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: order-configmap
    envs:
      - .env

resources:
- deployment.yaml
- service.yaml
