apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order
  name: order
spec:
  ports:
  - name: 80-8080
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: order
  type: ClusterIP
status:
  loadBalancer: {}
