apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
  namespace: kubetools
spec:
  ports:
    - name: grpc
      port: 5002
      targetPort: 5002
  selector:
    app: order
